### ISSUE TITLE
parseJsonByLine causing compile-time errors related to GCAllocator

### ISSUE THREAD

**Issue by cym13** [tamediadigital/asdf#98]
Issue
=====

I am currently unable to compile even the simplest example with
parseJsonByLine. Even the simplest examples or those provided in
asdf/examples fail. Doing "dub test" also fails with the same error.

    $ cat source/app.d
    import asdf;
    void main() {
        `{"test": "should be ok"}`.parseJsonByLine;
    }
    $ dub build
    Performing "debug" build using /usr/bin/dmd for x86_64.
    asdf 0.2.2: target for configuration "library" is up to date.
    test3 ~master: building configuration "application"...
    ../.dub/packages/asdf-0.2.2/asdf/source/asdf/jsonparser.d(228,33): Error: constructor asdf.jsonparser.JsonParser!(false, true, false, shared(GCAllocator), string).JsonParser.this(ref shared(GCAllocator) allocator, string input) is not callable using argument types (shared(const(GCAllocator)), string)
    ../.dub/packages/asdf-0.2.2/asdf/source/asdf/jsonparser.d(228,33):        cannot pass argument instance of type shared(const(GCAllocator)) to parameter ref shared(GCAllocator) allocator
    source/app.d(5,21): Error: template instance `asdf.jsonparser.parseJsonByLine!(cast(Flag)true, cast(Flag)false, string)` error instantiating
    /usr/bin/dmd failed with exit code 1.

Version
=======

- DUB version 1.9.0, built on May  3 2018

- DMD64 D Compiler v2.080.0-dirty

- Archlinux x86_64

- ASDF commit '5977a322dd2cb3df4218a94fb12d10fda277a859'

Reproducing
===========

If that helps, here is a Dockerfile that exhibits the bug.

    FROM base/archlinux

    RUN pacman --noconfirm -Sy
    RUN pacman --noconfirm -S dub dmd git
    RUN git clone "https://github.com/tamediadigital/asdf" /opt/asdf
    RUN cd /opt/asdf && git checkout '5977a322dd2cb3df4218a94fb12d10fda277a859'

    CMD cd /opt/asdf && dub test

**Comment by cym13** [comment]
Complement of information:
==========================

It's weird, a git bisect puts the origin of the bug somewhere arround a year
ago (about eb0cb72b7385a987ec713157ba63e3c5bc329f40, I'm unsure because of
other, seemingly unrelated, compilation errors during bisecting).

However I definitely used asdf more recently. The most recent binary
successfully built with it on my system that I could find dates March the
31st.

Could it be due to a change in phobos/dmd?

**Comment by yannick** [comment]
Likely, could you maybe try withldc and older dmd?

**Comment by cym13** [comment]
I confirm it works fine with LDC.

    LDC - the LLVM D compiler (1.9.0):
      based on DMD v2.079.1 and LLVM 6.0.0
      built with LDC - the LLVM D compiler (1.9.0)
      Default target: x86_64-pc-linux-gnu
      Host CPU: sandybridge

**Comment by yannick** [comment]
i can reproduce it on `v2.080.0` on macOS.
@9il  any immediate idea?

whole error:
```
asdf 0.2.2+commit.3.g5977a32: building configuration "asdf-test-library"...
source/asdf/jsonparser.d(76,97): Error: constructor asdf.jsonparser.JsonParser!(true, true, false, shared(GCAllocator), Chunks!(const(ubyte)[])).JsonParser.this(ref shared(GCAllocator) allocator, Chunks!(const(ubyte)[]) input) is not callable using argument types (shared(const(GCAllocator)), Chunks!(const(ubyte)[]))
source/asdf/jsonparser.d(76,97):        cannot pass argument instance of type shared(const(GCAllocator)) to parameter ref shared(GCAllocator) allocator
source/asdf/jsonparser.d(88,24): Error: template instance `asdf.jsonparser.parseJson!(cast(Flag)true, cast(Flag)true, Chunks!(const(ubyte)[]))` error instantiating
source/asdf/jsonparser.d(228,33): Error: constructor asdf.jsonparser.JsonParser!(false, true, false, shared(GCAllocator), Chunks!(const(ubyte)[])).JsonParser.this(ref shared(GCAllocator) allocator, Chunks!(const(ubyte)[]) input) is not callable using argument types (shared(const(GCAllocator)), Chunks!(const(ubyte)[]))
source/asdf/jsonparser.d(228,33):        cannot pass argument instance of type shared(const(GCAllocator)) to parameter ref shared(GCAllocator) allocator
source/asdf/jsonparser.d(240,33): Error: template instance `asdf.jsonparser.parseJsonByLine!(cast(Flag)true, cast(Flag)false, Chunks!(const(ubyte)[]))` error instantiating
source/asdf/jsonparser.d(228,33): Error: constructor asdf.jsonparser.JsonParser!(false, true, false, shared(GCAllocator), string).JsonParser.this(ref shared(GCAllocator) allocator, string input) is not callable using argument types (shared(const(GCAllocator)), string)
source/asdf/jsonparser.d(228,33):        cannot pass argument instance of type shared(const(GCAllocator)) to parameter ref shared(GCAllocator) allocator
source/asdf/jsonparser.d(255,39): Error: template instance `asdf.jsonparser.parseJsonByLine!(cast(Flag)true, cast(Flag)false, string)` error instantiating
source/asdf/jsonparser.d(76,97): Error: constructor asdf.jsonparser.JsonParser!(true, true, false, shared(GCAllocator), Chunks!(immutable(ubyte)[])).JsonParser.this(ref shared(GCAllocator) allocator, Chunks!(immutable(ubyte)[]) input) is not callable using argument types (shared(const(GCAllocator)), Chunks!(immutable(ubyte)[]))
source/asdf/jsonparser.d(76,97):        cannot pass argument instance of type shared(const(GCAllocator)) to parameter ref shared(GCAllocator) allocator
source/asdf/jsonparser.d(1272,28): Error: template instance `asdf.jsonparser.parseJson!(cast(Flag)true, cast(Flag)true, Chunks!(immutable(ubyte)[]))` error instantiating
source/asdf/jsonparser.d(76,97): Error: constructor asdf.jsonparser.JsonParser!(true, true, false, shared(GCAllocator), MapResult!(__lambda1, Chunks!(immutable(ubyte)[]))).JsonParser.this(ref shared(GCAllocator) allocator, MapResult!(__lambda1, Chunks!(immutable(ubyte)[])) input) is not callable using argument types (shared(const(GCAllocator)), MapResult!(__lambda1, Chunks!(immutable(ubyte)[])))
source/asdf/jsonparser.d(76,97):        cannot pass argument instance of type shared(const(GCAllocator)) to parameter ref shared(GCAllocator) allocator
source/asdf/jsonparser.d(1327,30): Error: template instance `asdf.jsonparser.parseJson!(cast(Flag)true, cast(Flag)true, MapResult!(__lambda1, Chunks!(immutable(ubyte)[])))` error instantiating
source/asdf/jsonparser.d(228,33): Error: constructor asdf.jsonparser.JsonParser!(false, true, false, shared(GCAllocator), ByChunkImpl).JsonParser.this(ref shared(GCAllocator) allocator, ByChunkImpl input) is not callable using argument types (shared(const(GCAllocator)), ByChunkImpl)
source/asdf/jsonparser.d(228,33):        cannot pass argument instance of type shared(const(GCAllocator)) to parameter ref shared(GCAllocator) allocator
source/asdf/package.d(36,4): Error: template instance `asdf.jsonparser.parseJsonByLine!(cast(Flag)true, cast(Flag)false, ByChunkImpl)` error instantiating
dmd failed with exit code 1.
```

**Comment by yannick** [comment]
@cym13  reason is https://github.com/dlang/phobos/commit/d0adf134a54928b8e71c7ffa9baa2f3c54ff6d86#diff-7bdcefb6c10b87dd8d35d34bad73711d

however i'm not 100% sure how to fix it, the default template needs to be adjusted i guess

**Comment by 9il** [comment]
https://github.com/tamediadigital/asdf/releases/tag/v0.2.3
